---
- name: Deploy image with auto-rollback
  hosts: localhost 
  become: false 
  gather_facts: no
  vars: 
     DEPLOYMENT_NAME: "flask-deployment"
     LATEST_IMAGE: "{{docker_username}}/app_deployment:latest"
  tasks:
      - name: Create deployment
        command: "kubectl apply -f kubernetes/deploy.yaml"
      - name: Create service
        command: "kubectl apply -f kubernetes/service.yaml"
    
