---
- name: Deploy image with auto-rollback
  hosts: localhost 
  become: false 
  gather_facts: no
  vars: 
     DEPLOYMENT_NAME: "flask-deployment"
     LATEST_IMAGE: "{{docker_username}}/app_deployment:latest"
  tasks:
      - name: Get current version 
        command: "kubectl rollout history deployment/{{DEPLOYMENT_NAME}}"
        register: rollout_history
        ignore_errors: true
        changed_when: false
      - name: Extract previous version number
        set_fact:
            PREVIOUS_REVISION: "{{ (rollout_history.stdout_lines[-2].split()[0] | int) - 1}}" 
        when: rollout_history.stdout_lines | length > 1
        ignore_errors: true
      - block:
          - name: Update deployment image
            command: "kubectl set image deployment/{{DEPLOYMENT_NAME}} flask-app={{LATEST_IMAGE}}"
          - name: Wait for rollout to succeed
            command: kubectl rollout status deployment/flask-deployment
            register: rollout_status
            until: rollout_status.rc == 0
            retries: 10
            delay: 10 
        rescue:
          - name: Rollback to previous version
            command: "kubectl rollout undo deployment/flask-deployment revision=Previous_version" 
            when: Previous_version is defined
          - name: Fail if rollback unsuccessful
            fail:
               msg: "Deployment failed and rollback was also unsuccessful"   
    
