apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-deployment
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-deployment
    spec:
      containers:
        - image: raghav045/app_deployment:v2
          name: flask-app
          ports:
           - containerPort: 9001
